version: '3.8'

services:  
  node-app:
    build: ./app/
    environment:
      - NODE_ENV=dev
      - MONGODB_URL= 'mongodb://mongo_db:27017'
    ports:
      - '4000:4000'
    depends_on:
      - mongo_db
    volumes:
      - .:/code
    networks:
      - node-network

  mongo_db:
    image: mongo:latest
    
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    networks:
      - node-network

volumes:
  dbdata6: {}

networks:
  node-network:
    driver: bridge